### ISSUE TITLE
Correct `pyproject.toml` build-backend specification

### ISSUE THREAD

**Issue by nikitos3000** [pavdmyt/yaspin#107]
Currently:

https://github.com/pavdmyt/yaspin/blob/2c78d24eb2d1b31273f696e8d118b2c6721f1068/pyproject.toml#L75-L77

According to https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

> If your `pyproject.toml` file still references poetry directly as a build backend, you should update it to reference poetry_core instead.

Should be updated  to,

```toml
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

This will significantly speed up the package installation process, since the entire `poetry` dependency cone is currently being installed during isolated build per PEP517.

I can submit a PR if no objections.
